#define BOOST_MPL_PREPROCESSED_HEADER apply_wrap.hpp
#define BOOST_MPL_CFG_COMPILER_DIR plain

#define BOOST_PP_STRINGIZE(text) BOOST_PP_STRINGIZE_A((text))
#define BOOST_PP_STRINGIZE_A(arg) BOOST_PP_STRINGIZE_I arg
#define BOOST_PP_STRINGIZE_I(text) #text


#define AUX778076_PREPROCESSED_HEADER BOOST_MPL_CFG_COMPILER_DIR/BOOST_MPL_PREPROCESSED_HEADER /**/
#include BOOST_PP_STRINGIZE(parser/preprocessor/AUX778076_PREPROCESSED_HEADER)

