#!/usr/bin/env python

import os
import subprocess
import sys
import time
import urllib
from glob import glob
from shutil import copyfile
import re
import requests
import json

from sitedefs import SONAR_HOME, SONAR_VERSIONS, START_SCRIPT, STOP_SCRIPT

SONAR_URL = "http://localhost:9000"
LOGFILE_TMPL = os.path.join(SONAR_HOME, "sonarqube-%s", "logs", "sonar.log")
SONAR_PLUGINS_TMPL = os.path.join(SONAR_HOME, "sonarqube-%s", "extensions", "plugins")
SONAR_ERROR_RE = re.compile(".* ERROR .*")
SONAR_WARN_RE = re.compile(".* WARN .*")
INDENT = "    "
PROJECT_KEY = "smoketest_project1"
PROJECT_PATH = "../resources/org/sonar/plugins/cxx/smoketest_project1"
BASEDIR = os.path.dirname(os.path.realpath(__file__))
JAR_PATH = os.path.normpath(glob(os.path.join(BASEDIR, "../../../target/*SNAPSHOT.jar"))[0])

EXP_MEASURES = {
    # size metrics
    "ncloc": 56.0,
    "lines": 148.0,
    "statements": 36,
    "classes": 1,
    "files": 8.0,
    "directories": 5.0,
    "functions": 5.0,

    # comments / documentation
    "comment_lines_density": 30.0,
    "comment_lines": 24.0,

    # duplications
    "duplicated_lines_density": 58.1,
    "duplicated_lines": 86,
    "duplicated_blocks": 2,
    "duplicated_files": 2,

    # complexity
    "complexity": 7,
    "function_complexity": 1.4,
    "file_complexity": 0.9,
    "class_complexity": 6.0,
 
    # violations
    "violations": 12,
    "violations_density": 57.1,

    # coverage statistics
    "coverage": 84.0,
    "line_coverage": 100.0,
    "branch_coverage": 50.0,
    "it_coverage": 84.0,
    "it_line_coverage": 100.0,
    "it_branch_coverage": 50.0,
    "overall_coverage": 84.0,
    "overall_line_coverage": 100.0,
    "overall_branch_coverage": 50.0,

    # design/tangles
    "package_tangle_index": 100,
    "package_tangles": 1.0,
  
    # test execution statistics
    "test_success_density": 60.0,
    "test_failures": 2.0,
    "test_errors": 0.0,
    "tests": 5.0
    }

RED = ""
GREEN = ""
RESET = ""
RESET_ALL = ""
BRIGHT = ""
try:
    import colorama
    colorama.init()
    RED = colorama.Fore.RED
    GREEN = colorama.Fore.GREEN
    RESET = colorama.Fore.RESET
    BRIGHT = colorama.Style.BRIGHT
    RESET_ALL = colorama.Style.RESET_ALL
except ImportError:
    pass


def test_bootup(version):
    print(BRIGHT + "\nRunning smoke test for Sonar %s" % version + RESET_ALL)

    if is_installed(version):
        cleanup(version)
        install_plugin(version)
        started = start_sonar(version)
        logsOK = checkSonarLogs(version)
        analysisFinishedOk = runAnalysis(version)
        resultingMetricsOk = checkMetrics()
        stop_sonar(version)
        return all([started, logsOK, analysisFinishedOk, resultingMetricsOk])
    else:
        sys.stdout.write(INDENT + RED + "not available\n" + RESET)
        return False


def cleanup(version):
    sys.stdout.write(INDENT + "cleaning logs ... ")
    sys.stdout.flush()
    try:
        os.remove(sonarLogFile(version))
    except OSError:
        pass
    sys.stdout.write(GREEN + "OK\n" + RESET)


def is_installed(version):
    return os.path.exists(START_SCRIPT % version)


def install_plugin(version):
    sys.stdout.write(INDENT + "copying jar ... ")
    sys.stdout.flush()
    for path in glob(os.path.join(SONAR_PLUGINS_TMPL % version, "sonar-cxx*.jar")):
        os.remove(path)
    copyfile(JAR_PATH, os.path.join(SONAR_PLUGINS_TMPL % version, os.path.basename(JAR_PATH)))
    sys.stdout.write(GREEN + "OK\n" + RESET)


def start_sonar(version):
    sys.stdout.write(INDENT + "starting Sonar ... ")
    sys.stdout.flush()
    now = time.time()
    rc = subprocess.call(start_script(version), stdout=subprocess.PIPE, shell = (os.name == "nt"))
    if rc != 0 or not wait_for_sonar(50, is_webui_up):
        sys.stdout.write(RED + "FAILED\n" + RESET)
        return False

    sys.stdout.write(GREEN + "OK, duration: %03.1f s\n" % (time.time() - now)
                     + RESET)
    return True


def stop_sonar(version):
    sys.stdout.write(INDENT + "stopping Sonar ... ")
    sys.stdout.flush()
    rc = subprocess.call(stop_script(version), stdout=subprocess.PIPE, shell = (os.name == "nt"))
    if rc != 0 or not wait_for_sonar(30, is_webui_down):
        sys.stdout.write(RED + "FAILED\n" + RESET)
        return False

    sys.stdout.write(GREEN + "OK\n" + RESET)
    return True


def start_script(version):
    res = START_SCRIPT % version
    if os.name != "nt":
        res = [res, "start"]
    return res


def stop_script(version):
    res = STOP_SCRIPT % version
    if os.name != "nt":
        res = [res, "stop"]
    return res


def sonarLogFile(version):
    return LOGFILE_TMPL % version


def wait_for_sonar(timeout, criteria):
    for _ in range(timeout):
        if criteria():
            return True
        time.sleep(1)
    return False


def is_webui_up():
    try:
        return urllib.urlopen(SONAR_URL).getcode() == 200
    except IOError:
        return False


def is_webui_down():
    try:
        urllib.urlopen(SONAR_URL)
        return False
    except IOError:
        return True


def checkSonarLogs(version):
    sys.stdout.write(INDENT + "logs check ... ")
    sys.stdout.flush()
    badlines = []
    errors = warnings = 0
    try:
        with open(sonarLogFile(version), "r") as log:
            lines = log.readlines()
            errors = warnings = 0
            for line in lines:
                if isSonarError(line):
                    badlines.append(line)
                    errors += 1
                elif isSonarWarning(line):
                    badlines.append(line)
                    warnings += 1
        reslabel = (RED + "FAILED\n") if errors > 0 else (GREEN + "OK\n")
    except IOError, e:
        badlines.append(str(e) + "\n")
        reslabel = RED + "FAILED\n"

    sys.stdout.write(reslabel + RESET)

    if badlines:
        for line in badlines:
            sys.stdout.write(2*INDENT + line)

    summary_msg = "%i errors and %i warnings\n" % (errors, warnings)

    print(2*INDENT + len(summary_msg) * "-")
    print(2*INDENT + summary_msg)
    return errors == 0


def isSonarError(line):
    return SONAR_ERROR_RE.match(line)


def isSonarWarning(line):
    return SONAR_WARN_RE.match(line)


def runAnalysis(version):
    logfname = "analysis_%s.log" % version
    sys.stdout.write(INDENT + "running analysis (see %s) ... " % logfname)
    sys.stdout.flush()
    now = time.time()
    runner = "sonar-runner.bat" if os.name == 'nt' else "sonar-runner"
    with open(logfname, "w") as logfile:
        rc = subprocess.call([runner, "-X"],
                             cwd=os.path.join(BASEDIR, PROJECT_PATH),
                             stdout=logfile, stderr=logfile)
    if rc == 0:
        label = GREEN + "OK, duration: %03.1f s\n" % (time.time() - now)
    else:
        label = RED + "FAILED\n"

    sys.stdout.write(label + RESET)

    return rc == 0


def diffDicts(d1, d2):
    rc = True
    difflist = []
    if d1 != d2:
        rc = False
        for k1, v1 in d1.iteritems():
            v2 = d2.get(k1, None)
            if v1 != v2:
                difflist.append("%s %s/%s" % (k1, str(v1), str(v2)))
    return rc, ", ".join(difflist)


def checkMetrics():
    sys.stdout.write(INDENT + "checking resulting metrics ... ")
    sys.stdout.flush()

    rc = False
    try:
        url = (SONAR_URL + "/api/resources?resource=" + PROJECT_KEY + "&metrics="
               + ",".join(EXP_MEASURES.keys()))
        r = requests.get(url)
        gotMeasures = _toSimpleDict(json.loads(r.text)[0]["msr"])

        rc, diff = diffDicts(EXP_MEASURES, gotMeasures)
        label = (GREEN + "OK") if rc else (RED + "FAILED, diff: " + diff)
    except requests.exceptions.ConnectionError, e:
        label = RED + "FAILED, reason: " + str(e)

    sys.stdout.write(label + "\n" + RESET)

    return rc


def _toSimpleDict(measures):
    return {measure["key"]: measure["val"] for measure in measures}


if __name__ == "__main__":
    if is_webui_up():
        print "Sonar seems to be running, exit it first"
        sys.exit(-1)

    badversions = []
    goodversions = []
    for sonar_version in SONAR_VERSIONS:
        if test_bootup(sonar_version):
            goodversions.append(sonar_version)
        else:
            badversions.append(sonar_version)

    print
    print BRIGHT + "Summary:" + RESET_ALL
    print INDENT + "Tests succeded for: " + GREEN + ", ".join(goodversions) + RESET
    print INDENT + "Tests failed for: " + RED + ", ".join(badversions) + RESET

    sys.exit(len(badversions) != 0)
